blank_issues_enabled: false
contact_links:
  - name: Apeira Discord Server
    url: https://discord.gg/cHQbhZSn2w
    about: Get quick community help here.
  - name: Discussions
    url: https://github.com/apeira/Torch/discussions
    about: Not sure what to choose? Start a discussion instead.